apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: catalog-service
  name: catalog-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9001
  selector:
    app: catalog-service
status:
  loadBalancer: {}
